In [1]:
print("2ECEB MART SAFINI V. VELONZA")

2ECEB MART SAFINI V. VELONZA


NORMALIZATION PROBLEM

In [1]:
import numpy as np

In [2]:
x = np.random.random((5,5))

In [3]:
normx = (x - x.mean())/x.std()

In [7]:
np.save("X_normalized.npy", normx)

In [8]:
x

array([[0.90616362, 0.87427276, 0.99583014, 0.18747656, 0.16811795],
       [0.7463114 , 0.30895975, 0.12762786, 0.37492776, 0.07315797],
       [0.11741335, 0.20412736, 0.60957881, 0.12867233, 0.34369321],
       [0.06358627, 0.77640374, 0.44816043, 0.12816861, 0.45548907],
       [0.92425801, 0.62233521, 0.28772404, 0.37176643, 0.95106935]])

In [9]:
n = np.load("X_normalized.npy")
n

array([[ 1.47863603e+00,  1.37575663e+00,  1.76789877e+00,
        -8.39836927e-01, -9.02287484e-01],
       [ 9.62955327e-01, -4.47934095e-01, -1.03290789e+00,
        -2.35122357e-01, -1.20862686e+00],
       [-1.06585972e+00, -7.86121718e-01,  5.21858184e-01,
        -1.02953842e+00, -3.35884520e-01],
       [-1.23950503e+00,  1.06003273e+00,  1.12506070e-03,
        -1.03116342e+00,  2.47671343e-02],
       [ 1.53700823e+00,  5.63010100e-01, -5.16440179e-01,
        -2.45320768e-01,  1.62350119e+00]])

-----------------------

DIVISIBLE BY 3 PROBLEM

In [39]:
import numpy as np

In [40]:
a = np.arange(1,101)

In [41]:
sqrnum = a ** 2

In [42]:
sqrnum.size

100

In [43]:
A = sqrnum.reshape(10,10)

In [44]:
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [45]:
divisibleby3 = A [A % 3 == 0]

In [46]:
divisibleby3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [47]:
np.save("divsible_by_3.npy", divisibleby3)

In [48]:
loaded = np.load("divsible_by_3.npy")

In [49]:
loaded

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])